# Generated by Django 4.2.3 on 2023-08-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick', models.CharField(max_length=50)),
                ('clinic', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
