# Generated by Django 4.2.3 on 2023-08-16 09:48

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick', models.CharField(max_length=50)),
                ('clinic', models.CharField(max_length=50)),
                ('typical_user', models.CharField(max_length=50)),
                ('nurse', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('date', django_jalali.db.models.jDateField(default='1402-01-01')),
                ('time', models.CharField(default='08:00', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RequestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick', models.CharField(max_length=50)),
                ('clinic', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
