# Generated by Django 4.2.3 on 2023-08-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('number', models.IntegerField(default=1)),
                ('clinic', models.CharField(max_length=30)),
                ('typical_user', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='requestsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
