# Generated by Django 4.2.3 on 2023-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_service'),
        ('registeration', '0003_service_visitappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterField(
            model_name='visitappointment',
            name='services',
            field=models.ManyToManyField(blank=True, to='managment.service'),
        ),
    ]
