# Generated by Django 4.2.3 on 2023-08-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='user_type',
        ),
    ]
