# Generated by Django 4.2.3 on 2023-08-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0007_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Clinic_Admin', 'CA'), ('Typical_User', 'TU'), ('Nurse', 'N'), ('Sick', 'S'), ('Warehouse_Keeper', 'WK'), ('Financial_Manager', 'FM')], max_length=20, null=True),
        ),
    ]
