# Generated by Django 4.2.3 on 2023-08-14 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0008_user_image_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managment.category', to_field='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='wharehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managment.wharehouse', to_field='name'),
        ),
    ]
