# Generated by Django 4.2.3 on 2023-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0009_alter_clinic_manager_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
